version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/ragchat
      # ベクトル検索設定（オプション）
      # - DEBUG=false
      # - EMBEDDING_MODEL_NAME=intfloat/multilingual-e5-large
      # - VECTOR_DB_PATH=./vector_db
      # - DEFAULT_SEARCH_RESULTS=5
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./vector_db:/app/vector_db
      - ./backend/.env:/app/.env:ro # .envファイルを読み取り専用でマウント
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ragchat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
