name: Backend Test

# トリガー設定
on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-test.yml"
      - "codecov.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-test.yml"
      - "codecov.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - uses: actions/checkout@v4

      # Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Python 3.12を使用

      # 依存関係のインストール
      - name: Install dependencies
        working-directory: ./backend # backendディレクトリで実行
        run: |
          python -m pip install --upgrade pip  # pipを最新に更新
          # requirements.txtが存在する場合のみインストール
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Lint・カバレッジ・フォーマット用パッケージをインストール
          pip install flake8 pytest-cov black

      # フォーマットチェック
      - name: Check code formatting
        working-directory: ./backend
        run: |
          # blackによるフォーマットチェック
          black --check app/ tests/

      # Lint実行
      - name: Run lint
        working-directory: ./backend
        run: |
          # コードの品質チェック
          flake8 app/ tests/ --max-line-length=88

      # テストとカバレッジの実行
      - name: Run tests with coverage
        working-directory: ./backend # backendディレクトリで実行
        run: |
          python -m pytest -v tests/ --cov=app --cov-report=term-missing --cov-report=xml

      # カバレッジ結果をCodecovに送信
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./backend/coverage.xml
          flags: backend
          name: backend-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ./backend
